name: ${project.name}
version: ${project.version}
author: CubBossa
main: main.java.bossascrew.pathfinder.PathPlugin
api-version: 1.16

depends: ["bossascrew-core-bukkit"]

commands:
  cancelpath:
  editmode-visualizer:
  finde:
  nodegroup:
  pathsystem:
  roadmap:
  waypoint:
