name: ${project.name}
version: ${project.version}
author: CubBossa
main: de.bossascrew.pathfinder.PathPlugin
api-version: 1.16

depend:
  - bossascrew-core-bukkit
  - ProtocolLib

softdepend:
  - dtlTradersPlus
  - Citizens